name: CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          runtime: node@22
          cache: true
          install: false

      - name: Install
        env:
          HUSKY: '0'
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test
